### ISSUE TITLE
question for supporting multiple roomba's

### ISSUE THREAD

**Issue by DoctorOgg** [relm923/MMM-Roomba#1]
how would one support more than one rooma?

**Comment by relm923** [comment]
I only have one Roomba but I should be able to add multi support fairly easily. I'll ping you once I'm done but for now you can add multiple copies of the same widget as a stop gap

**Comment by DoctorOgg** [comment]
i tried adding multiple instances, however, they seem to only read one of the Roomba settings

**Comment by relm923** [comment]
Looks like a limitation of MagicMirror unfortunately. You'd need to give each instance a unique name ad install multiple copies of `MMM-Roomba` under the unique names.

I can add multi-roomba support but it will require a breaking config change. I'll try to get to soon

**Comment by relm923** [comment]
Added multiple Roomba support on [mutli_robot_support](https://github.com/relm923/MMM-Roomba/tree/mutli_robot_support) branch. I haven't fully tested it yet but feel free to give it a shot.

**Comment by TATUMTOT** [comment]
ok I just tested and if the module is enabled the magic mirror wont load. Hopfully we can get this working.

**Comment by TATUMTOT** [comment]
@relm923 I have it working with Multiple Instances of MMM-Roomba. I have 3 Roomba's Displaying their status 2X S9+ and 1X 985

![image](https://user-images.githubusercontent.com/11933561/69320451-13c8ab80-0bf6-11ea-8050-593fd779f3a3.png)

**Comment by relm923** [comment]
Is there still interest in support multiple devices? @TATUMTOT @DoctorOgg

**Comment by TATUMTOT** [comment]
@relm923 I had to copy the mmm-roomba 3 times for mine. Then go edit the code to make each of them unique. So I have mmm-roomba and then mmm-roomba1 and so on.

**Comment by relm923** [comment]
Thanks @TATUMTOT I'll take another look at it. Unfortunately it's difficult for me to test with only one device

**Comment by relm923** [comment]
@TATUMTOT did you get errors when attempting to use the [mutli_robot_support](https://github.com/relm923/MMM-Roomba/tree/mutli_robot_support) branch?

**Comment by TATUMTOT** [comment]
@relm923 i remember you talking about is but i never got it to work. Or the directions were not clear. But i think it just did not show the second one.

**Comment by relm923** [comment]
@TATUMTOT mind pulling the latest version of that branch and trying again? You'll need to update your config to pass the robot metadata as a list:

```js
var config = {
    modules: [
        {
            module: 'MMM-Roomba',
            position: 'top_right',
            header: 'Roomba', // Optional
            config: {
                // See below for configurable options
                robots: [
                    {
                        username: 'xxxxxxxxxxxxx',
                        password: ':1:1486937829:gktkDoYpWaDxCfGh',
                        ipAddress: '192.168.1.44'
                    }
                    {
                        username: 'xxxxxxxxxxxxx',
                        password: ':1:1486937829:gktkDoYpWaDxCfGh',
                        ipAddress: '192.168.1.45'
                    }
                ]
            }
        }
    ]
}
```

**Comment by TATUMTOT** [comment]
@relm923 I have not had time to redo this. I have to fully redo it. Roombas have been swapped out for replacements and still have not gotten arround to re-registering the API's.

**Comment by Kanostic** [comment]
Having issues with getting this module to work, I am getting "Config.username is required for module:MMM-Roomba.  
![MMM-](https://user-images.githubusercontent.com/8622831/116361342-b9058d00-a7b5-11eb-8808-ab251666e6eb.png)

Below is what I have in my config, replaced the username and password for sharing.
               {
                module: 'MMM-Roomba',
                position: 'middle_center',
                header: 'Bender', // Optional
                config: {
                    // See below for configurable options
                    robots: [
                        {
                            username: 'xxxxxxxxxxxxxx',
                            password: 'xxxxxxxxxxxxxx',
                            ipAddress: '192.168.86.114',
                    }
                   ]
                  }

I do have multiple roombas, just trying to get one to work.

Thanks

**Comment by relm923** [comment]
@Kanostic what branch are you using?

**Comment by relm923** [comment]
The latest version (2.0.0) now support multiple robots. You'll need to update your `config.js` to match the new format. See the README for an example
